name: Deploy gh-pages CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x, 20.x]

        steps:
            - uses: actions/checkout@v3
            - name: setup-node
              uses: actions/setup-node@v3
            - run: npm install
            - run: npm run deploy
            - run: git config --global user.email "gvao@gmail.com"
            - run: git config --global user.name "Yuri Galvão"
          
